name: Dance the Hamster dance!

on:
  release:
    types: [released]
  workflow_dispatch:
    inputs:
      TAG_NAME:
        description: 'Tag. Your it!'
        required: false

env:
  TAG_NAME: 420
permissions:
  contents: write

jobs:
  update_tag:
    name: Do it yourself!
    environment:
      name: releaseNewActionVersion
    runs-on: macos-12
    steps:
      - name: Update the ${{ env.TAG_NAME }} tag
        uses: actions/publish-action@v0.2.2
